# Generated by Django 4.2.26 on 2025-11-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
    ]
