# Generated by Django 4.2.26 on 2025-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20251120_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
